using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace test_premium_thing
{
    internal class NoteBooks
    {

        internal static void LogNoteBook()
        {

            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();
            Logs.Log(""); Console.ReadLine();

        } internal static void NoneLogNotBook()
        {

            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();


        }

    }
}
